### PR TITLE
Add support for users groups

### PR DESCRIPTION
**Pull request by soliverr**
Add users' groups for group file provider: https://trino.io/docs/current/security/group-file.html#file-format

### CODE REVIEW

**Comment by mosabua** [comment]
@nineinchnick @ebyhr @hashhar  .. this looks simple enough and good to me .. wdyt?

**Review by nineinchnick — APPROVED** [review]

**Comment by mosabua** [comment]
Can you squash commits please.

**Comment by andreyolv** [comment]
This feature is extremely important. How does this not exist on the official chart yet?

**Comment by soliverr** [comment]
> Can you squash commits please.

Left only my changes in PR.

**Review by mosabua — APPROVED** [review]
Looks good.

**Pull request merged**
