### PR TITLE
add check if passwordAuthSecret is using

### PR DESCRIPTION
**Pull request by vladimir4862**
Add check if 
`Values.auth.passwordAuthSecret` is set together with `Values.auth.groups`  and don't make secret with the name `trino.fileAuthSecretName`  
But retain the code to import this as volume.

### CODE REVIEW

**Comment by nineinchnick** [comment]
@cla-bot check

**Comment by vladimir4862** [comment]
@cla-bot check

**Comment by vladimir4862** [comment]
@cla-bot check

**Comment by vladimir4862** [comment]
@cla-bot check

**Comment by nineinchnick** [comment]
@vladimir4862 you can also monitor the https://github.com/trinodb/cla/ repo, it's updated roughly every 2 weeks.

**Comment by nineinchnick** [comment]
When did you send your signed CLA?

**Comment by vladimir4862** [comment]
Hi. 
sorry for this noise. I didn't check "cla" repo 😸 
I send this on last Friday.

will check in cla repo next time. 
thanks

**Comment by nineinchnick** [comment]
No problem! I'm also keeping an eye on it.

**Comment by robertpikmets** [comment]
Related to this issue: https://github.com/trinodb/charts/issues/188.

I'd argue there's a scenario when a secret has to be created (containing group.db) even when `.Values.auth.passwordAuthSecret` hasn't been defined. So the final fix might be a bit more involved.

**Comment by sdaberdaku** [comment]
@robertpikmets I agree. For instance, if using oauth2 authentication, you might still need to use the group provider to assign users to groups while not requiring a passwords.db file at all.

**Pull request closed without merging**
