### PR TITLE
Update Trino to 448

### PR DESCRIPTION
**Pull request by nineinchnick**
Also, update the chart version to trigger a new release.

### CODE REVIEW

**Review by wendigo — APPROVED** [review]

**Comment by mosabua** [comment]
Don't we have to update the JVM config that comes out of the box with the chart or is this cleanly only using the one from the container and updating that.. 

If we update and merge this .. will the chart still be working with earlier releases .. given the current change I think the answer is yes.. but can you confirm?

**Comment by nineinchnick** [comment]
> If we update and merge this .. will the chart still be working with earlier releases .. given the current change I think the answer is yes.. but can you confirm?

This is a great idea for another test in the CI!

**Comment by wendigo** [comment]
448 was released, please update @nineinchnick

**Comment by nineinchnick** [comment]
@wendigo PTAL, especially on the JVM flags update.

We can now add more complex tests, enabling more/most features supported in the chart.

**Comment by mosabua** [comment]
This looks good but are you sure you want this order of commits? Typically I think its easier to do the release update/tagging as a separate PR.

**Comment by nineinchnick** [comment]
@mosabua I made sure the version bump commit is the last one, esp. after running all tests.

**Comment by wendigo** [comment]
We need to add a workaround for the g1 pinning issue @nineinchnick

**Comment by nineinchnick** [comment]
What workaround?

**Comment by nineinchnick** [comment]
I cancelled the release workflow: https://github.com/trinodb/charts/actions/runs/9138540987

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/pull/21999

**Pull request merged**
