### PR TITLE
make password work with other auth types

### PR DESCRIPTION
**Pull request by florianMalbranque**
rebased version of [PR-86](https://github.com/trinodb/charts/pull/86)

### CODE REVIEW

**Comment by florianMalbranque** [comment]
PTAL @losipiuk

**Comment by losipiuk** [comment]
Can you explain what you achieve with this change. Preferably in commit message.

**Comment by accbel** [comment]
When a Trino cluster is configured to work with multiple authentication types through server.config.authenticationType key (e.g PASSWORD,OAUTH2), the password-authenticator.properties key is not configured in coordinator configmap because its template expects that authenticationType must equals to "PASSWORD". This prevents password authentication type to work and cluster coordinator to start.

**Comment by losipiuk** [comment]
> @losipiuk, rephrased commit message to make it more self explanatory

Thanks. There is a typo. Please make summary
```
Allow password authentication to be used with other authentication types
```

And put https://github.com/trinodb/charts/pull/124#issuecomment-1898841283 as commit message body.


LGTM otherwise

**Comment by florianMalbranque** [comment]
Amended

**Review by losipiuk — APPROVED** [review]

**Pull request merged**
