### PR TITLE
Add secret mounts for both Coordinator and Worker

### PR DESCRIPTION
**Pull request by kempspo**
This PR turns the original `secretMount` to be added to both the Coordinator and Worker Containers.
It also adds a separate `coordinator.secretMount` and `worker.secretMount` for cases where the mount isn't needed on both.

Not sure if this is the best way, but was trying to solve an issue I was facing while trying to use the hive connector with GCS buckets. Since Google loves using the service_account.json pattern, needed to be able to mount that as a secret to the worker nodes for the Hive Connector to use.

### CODE REVIEW

**Comment by uqix** [comment]
We need this to specify kafka.properties too.

**Comment by yoshi-rk** [comment]
We need this too.

**Comment by mosabua** [comment]
@kempspo can you send a CLA and resolve conflicts here?

**Comment by mosabua** [comment]
Replaced by https://github.com/trinodb/charts/pull/98

**Pull request closed without merging**
