### PR TITLE
add ldap support for password auth

### PR DESCRIPTION
**Pull request by derbeneviv**
Hi all!  
Thanks for a great chart, but it lacks some functionality.

In our environment we needed to use a ldap auth, so i've added this to a chart, and am hoping this can be merged to upstream

### CODE REVIEW

**Comment by nineinchnick** [comment]
@derbeneviv are you still interested in working on this? We should have tests for this, which would require running an LDAP server. Maybe we can discuss how to best do this.

**Comment by alexagc** [comment]
Hi @nineinchnick we are interested in add this support, maybe i can continue with this work but as far i see seen promising and dont need much changes

**Comment by nineinchnick** [comment]
@alexagc can you always open up a second PR with these changes. The implementation looks fine, but it definitely needs tests.

**Comment by derbeneviv** [comment]
sorry for the delayed response
i'm interested (well i've implemented it in my fork) but i'm not really ready to sign anything, you can freely use any code from this PR

**Comment by nineinchnick** [comment]
We cannot accept any contributions without the CLA, so I have to close this.

**Pull request closed without merging**
