### PR TITLE
import valeriano manassero chart version improvements

### PR DESCRIPTION
**Pull request by valeriano-manassero**
this is a first proposal to import improvements we have in https://github.com/valeriano-manassero/helm-charts/tree/main/valeriano-manassero/trino before depreciating it in favour of the official one.

I know this PR is pretty big but I tested before submitting and seems to work on my testing environment, any thought is appreciated.

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
> @valeriano-manassero Should we retry :-) ? I would like to help.

I updated my fork with my chart again. I understand the PR is quite big since implementations are quite different; I checked file by file and importing features one by one is time consuming for me so I'm not sure this PR will be good for the maintainers.

**Comment by valeriano-manassero** [comment]
> @valeriano-manassero you need to sign the CLA if you want it to be considered for inclusion.

whoops, I totally missed it, mail sent.

**Comment by valeriano-manassero** [comment]
Since I see features importing is an ongoing process I don't see value on maintaining this PR :-)

**Comment by hashhar** [comment]
Thanks @valeriano-manassero for keeping the changes incoming in your chart. We seem to have ported over most of the big-ticket items but there are obviously a few more quality of life changes remaining.

I'll take a look at the missing features this weekend and decide which ones to port in what order accordingly.

**Pull request closed without merging**
