### PR TITLE
add hpa behavior

### PR DESCRIPTION
**Pull request by florianMalbranque**
add hpa behavior & bump autoscaling api to v2

### CODE REVIEW

**Comment by florianMalbranque** [comment]
@cla-bot check

**Comment by florianMalbranque** [comment]
@losipiuk @sopel39 PTAL 🙏

**Review by nineinchnick — APPROVED** [review]

**Review by losipiuk — APPROVED** [review]

**Comment by florianMalbranque** [comment]
@losipiuk Any visibility on when a new Trino chart version will be released ?

**Comment by losipiuk** [comment]
> @losipiuk Any visibility on when a new Trino chart version will be released ?

@mosabua is it just about bumping version and CI will do the job?

**Comment by florianMalbranque** [comment]
@losipiuk To me we just need to bump chart version, [Github action on main branch takes care of the rest](https://github.com/trinodb/charts/actions/runs/7184542911/job/19565929558)
could you please also merge [resource groups PR
](https://github.com/trinodb/charts/pull/119) before bumping ?

**Comment by losipiuk** [comment]
> @losipiuk To me we just need to bump chart version, [Github action on main branch takes care of the rest](https://github.com/trinodb/charts/actions/runs/7184542911/job/19565929558) could you please also merge [resource groups PR ](https://github.com/trinodb/charts/pull/119) before bumping ?

Sorry - did not notice - can you bump to 0.17?

**Comment by justrelax19** [comment]
@losipiuk Now with the help of above PR, can we use the hpa to autoscale the worker nodes based on our custom metrics ie does it support writing prometheus metrics or something to define the custom metrics

**Pull request merged**
