### PR TITLE
changing additionalJVMConfig to support [] instead of []

### PR DESCRIPTION
**Pull request by joshi95**
There is a bug in chart while supplying the additionalJVMConfig as the helm chart requires additionalJVMConfig to be an {} but it expects it to be [] in the template. Because of which the values do not update. This merge request should fix it. 

Have tested it for below values
worker:
  additionalJVMConfig:
    - "-Dcom.sun.management.jmxremote=true"
    - "-Dcom.sun.management.jmxremote.authenticate=false"
    - "-Dcom.sun.management.jmxremote.rmi.port=9081"
    - "-Dcom.sun.management.jmxremote.ssl=false"
coordinator:
  additionalJVMConfig:
    - "-Dcom.sun.management.jmxremote=true"
    - "-Dcom.sun.management.jmxremote.authenticate=false"
    - "-Dcom.sun.management.jmxremote.rmi.port=9081"
    - "-Dcom.sun.management.jmxremote.ssl=false"

### CODE REVIEW

**Review by hashhar — CHANGES_REQUESTED** [review]
The template should be fixed instead.

For populating files via volumes the convention has always been to use an object so you can set it like:

```yaml
obj: |-
  my content
  goes here
  and I don't need to escape or do anything special to the values
  and things get rendered as it is
```

**Comment by joshi95** [comment]
Sure, will change these.

**Comment by bitsondatadev** [comment]
@cla-bot recheck

**Comment by bitsondatadev** [comment]
> The template should be fixed instead.
> 
> For populating files via volumes the convention has always been to use an object so you can set it like:
> 
> ```yaml
> obj: |-
>   my content
>   goes here
>   and I don't need to escape or do anything special to the values
>   and things get rendered as it is
> ```

It seems like we're doing this across multiple additional property settings. Changing this is a breaking change that we should likely only do at once. Let's avoid making this a breaking change for now and I have filed trinodb/trino#15915 to track making this change all at once to remain consistent.

@hashhar, are you okay if we go back to the original version and merge this change and later we'll add a change to address the list issue?

**Comment by bitsondatadev** [comment]
For more context see: https://www.youtube.com/watch?v=TiLObiq1xog

**Comment by nineinchnick** [comment]
The default was fixed in 3239a09b4e1a93dfb8b2873285af36c016b21d50. I'll close this, but feel free to reopen after rebasing.

**Pull request closed without merging**
