### PR TITLE
Fixed warning about exchange.base-directory

### PR DESCRIPTION
**Pull request by soliverr**
Fixed warning about `exchange.base-directory`: rename to `exchange.base-directories`

### CODE REVIEW

**Comment by ckdarby** [comment]
Hey, @soliverr can you sign the CLA?

**Comment by soliverr** [comment]
Hi,
Sorry for delay. I was in relocating process last two month. I'll send signed CLA in a couple of days. Thanx, for remider me.

**Comment by soliverr** [comment]
I've signed and sent CLA. Something else?

**Comment by raunaqmorarka** [comment]
@cla-bot recheck

**Review by mosabua — APPROVED** [review]
This fixes the property name .. approved.

**Pull request merged**
