### PR TITLE
Merge coordinator & worker values into values.yaml

### PR DESCRIPTION
**Pull request by aksakalli**
I am getting an error for the newest version `0.6.0` with following instructions from the `README.md`:

```bash
helm repo add trino https://trinodb.github.io/charts/
helm install my-trino trino/trino --version 0.6.0 --dry-run --debug
```
gives:
```
Error: INSTALLATION FAILED: template: trino/templates/deployment-worker.yaml:64:30: executing "trino/templates/deployment-worker.yaml" at <.Values.worker.resources>: nil pointer evaluating interface {}.resources
```

`values.yaml` is the only default values file for helm charts and without specifying things like `.Values.worker.resources`, the chart fails.

`$ helm version` for reproducibility: 
```
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}
```

### CODE REVIEW

**Comment by aksakalli** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our [Contributor License Agreement](https://github.com/trinodb/cla/raw/master/Trino%20Foundation%20Individual%20CLA.pdf), and we don't seem to have you on file. In order for us to review and merge your code, please submit the signed CLA to [cla@trino.io](mailto:cla@trino.io). For more information, see https://github.com/trinodb/cla.

I signed it 3 days ago and I am still getting this message. 😞

**Comment by hashhar** [comment]
The CLA gets processed in batches. Thanks for sending the PR. Can you please make sure README.md for the chart is in sync? You can look at the `docs` failure log and it includes a diff of what's expected vs what's present.

**Comment by hashhar** [comment]
BTW see also https://github.com/trinodb/charts/pull/39

**Review by hashhar — APPROVED** [review]
I updated the chart version so that when I merge a new version gets released.

**Pull request merged**
