### PR TITLE
Add annotations to service resource

### PR DESCRIPTION
**Pull request by fr6nco**
Requested before, but never reached the main branch. The following PR adds an option to add annotations to the service object.

Version number incremented, no breaking changes present.

### CODE REVIEW

**Comment by Pluies** [comment]
This looks good to me fwiw 👍 

@hashhar This is a duplicate of #10, but I think this one is better – `with` is more idiomatic, and it has the default in the values file.

@fr6nco , can you sign the CLA to turn the checks here green?

**Comment by fr6nco** [comment]
CLA sent, updater readme with the annotations param

**Comment by bitsondatadev** [comment]
@cla-bot check

**Comment by fr6nco** [comment]
@cla-bot check

**Comment by mosabua** [comment]
Could you rebase and resolve conflicts. I can look at merging this.

**Comment by nineinchnick** [comment]
I'll close this, since there has been no activity here for a long time, and there's another PR superseding this one. Feel free to reopen after rebasing.

**Pull request closed without merging**
