### PR TITLE
Release both trino and trino-gateway charts

### PR DESCRIPTION
**Pull request by nineinchnick**
The gateway chart doesn't have any README yet, so don't try to publish it, only add the chart to the index.

### CODE REVIEW

**Comment by nineinchnick** [comment]
This doesn't work, because the chart needs to be committed in the repo, not just copied into the `charts` dir: https://github.com/helm/chart-releaser-action/blob/main/cr.sh#L293

**Comment by mosabua** [comment]
Maybe we have to do it the other way around .. run the build and such in the Trino Gateway repos as part of the release and publish to the github pages branch in the charts repo

**Comment by nineinchnick** [comment]
It's more about updating the chart index, than publishing it on GH pages. I don't want to hack the chart releaser too much, or adding a custom packaging step. I suggest copying (not moving) the chart into this repo. We can see how much work is it to keep it in sync with the gateway repo, and revisit this setup later. This has been working fine so far for Trino.

**Comment by mosabua** [comment]
Thats fine .. could we maybe just automate the copying the Trino Gateway charts into this repo with each Trino Gateway release .. and then doing the rest of the automation in the charts repo here?

**Pull request merged**
