### PR TITLE
Fix nil pointer evaluating interface

### PR DESCRIPTION
**Pull request by florianMalbranque**
Upgrading to 0.23.0, I get this error 

```
Error: template: trino/templates/ingress.yaml:33:25: executing "trino/templates/ingress.yaml" at <include "trino.fullname" .>: error calling include: template: trino/templates/_helpers.tpl:15:14: executing "trino.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
helm.go:84: [debug] template: trino/templates/ingress.yaml:33:25: executing "trino/templates/ingress.yaml" at <include "trino.fullname" .>: error calling include: template: trino/templates/_helpers.tpl:15:14: executing "trino.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```

This PR aims to fix nil pointer evaluating interface, by using $, which references the global scope in order to access the Values as expected.

### CODE REVIEW

**Comment by florianMalbranque** [comment]
@nineinchnick 👋 PTAL

**Review by nineinchnick — APPROVED** [review]
The same fix was suggested in #179. I'm inclined to merge this first since you have the CLA signed, and I could release a new version quicker.

**Comment by nineinchnick** [comment]
Can you also add a test, so we can avoid regressions like this in future?

**Comment by florianMalbranque** [comment]
Sure

**Pull request merged**
