### PR TITLE
feat: Add fsGroup option into securityContext

### PR DESCRIPTION
**Pull request by heitorrbarros**
[Related issue](https://github.com/trinodb/charts/issues/150)

### CODE REVIEW

**Comment by heitorrbarros** [comment]
@cla-bot check

**Comment by heitorrbarros** [comment]
Hi @nineinchnick, could you please help me review my PR?

**Comment by nineinchnick** [comment]
@heitorrbarros I recently added a more complete test in https://github.com/trinodb/charts/blob/main/test-values.yaml. Would you like to configure the cache usage in there so we can make sure that this change actually makes the volume writable?

**Comment by nineinchnick** [comment]
@heitorrbarros this would be superseded by #186. I'll close it since there was no activity here for a long time.

**Pull request closed without merging**
