### PR TITLE
Fixed typo in Trino JMX documentation

### PR DESCRIPTION
**Pull request by sdaberdaku**

### CODE REVIEW

**Comment by sdaberdaku** [comment]
@nineinchnick I figured out why the tests are failing. The Chart in the tests references the latest JMX exporter docker image which is broken.

**Comment by nineinchnick** [comment]
Let's pin it to the last working version, can you add it as a separate commit in this PR?

**Comment by sdaberdaku** [comment]
> Let's pin it to the last working version, can you add it as a separate commit in this PR?

sure thing!

**Comment by sdaberdaku** [comment]
@nineinchnick tests are working again now!

**Review by nineinchnick — APPROVED** [review]

**Pull request merged**
