### PR TITLE
Allow to set resources for the JMX Exporter container

### LINKED ISSUE #202: Unable to Set Resources for JMX Exporter in Trino Helm Chart
#### Description
Currently, the Trino Helm chart does not allow setting resource requests and limits for the JMX exporter. This limitation causes issues on Kubernetes clusters that require resource specifications for CPU and memory as a prerequisite.

#### Error Message
```
Error creating: pods "trino-helm-etl-coordinator-8655d99488-5jlwb" is forbidden: failed quota: quota-bitrino-dev: must specify limits.cpu for: jmx-exporter; limits.memory for: jmx-exporter; requests.cpu for: jmx-exporter; requests.memory for: jmx-exporter
```

#### Impact
This restriction prevents deployment on clusters with strict resource quota policies, hindering the ability to use the Trino Helm chart in such environments.

#### Suggested Solution
Please provide a way to configure resource requests and limits for the JMX exporter in the Helm chart values.

```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by rotem-ad**
Allows to set resources for the JMX Exporter container.
Resolves #202 for K8s clusters with strict resource quota policies.

### CODE REVIEW

**Review by nineinchnick — APPROVED** [review]

**Comment by nineinchnick** [comment]
@cla-bot check

**Comment by nineinchnick** [comment]
@rotem-ad can you rebase?

**Comment by nineinchnick** [comment]
@rotem-ad something went wrong with the rebase, the diff shows too many changes. Can you try again? If you're rebasing on the `main` branch in your repository, try updating it first, to match the remote repository.

**Comment by rotem-ad** [comment]
@nineinchnick done

**Comment by nineinchnick** [comment]
One last nitpick - please remove `Feature: ` from the commit message. It'll get added in release notes, and will be redundant with the section title.

**Comment by rotem-ad** [comment]
@nineinchnick done

**Pull request merged**
