### PR TITLE
Set appVersion and tag to 423

### PR DESCRIPTION
**Pull request by mosabua**
This has no real effect since the tag used is "latest" but 375 is very wrong... 420 is getting released today.

### CODE REVIEW

**Review by nineinchnick — APPROVED** [review]
If it doesn't have any effect it can be misleading. Can you add a comment explaining that?

**Comment by mosabua** [comment]
> If it doesn't have any effect it can be misleading. Can you add a comment explaining that?

I am not sure but maybe we should update the tag to be the same? Or alternatively, should this be set to "latest" ... 

Personally I think using "latest" as the actual tag is bad since it is a moving target and forces every users to override if they want a stable deployment. But maybe thats fine and we just need to update the documentation. Thoughts?

**Comment by nineinchnick** [comment]
I think we should pin it to a specific version and automate releases to follow Trino releases.

**Comment by mosabua** [comment]
Wdyt @nineinchnick @radek-starburst @losipiuk -- hardcoding to 423 is probably better than setting it to latest and having users get version updates without knowing.

**Review by nineinchnick — APPROVED** [review]

**Pull request merged**
